### ISSUE TITLE
Build "Judet Localitate" component

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/reusable-components#15]
We need to have a simple component for selecting the county and city.

<img width="1014" alt="componenta_localitate_judet" src="https://user-images.githubusercontent.com/15039873/87946428-a897e780-caaa-11ea-81a7-30c00b767b80.png">

When selecting the county, only the cities in that county are selected.

**Comment by ghost** [comment]
Hello, I'm sorry but there is a problem with the commit to my branch on reusable-components.
It tells me I have a whopping 1053 errors, and they are all related to prettier...
What should I do?

**Comment by dapetcu21** [comment]
I made a ton of changes on that repo. Added TypeScript amongst other things and did a number of other architectural changes. I wasn't aware somebody was still working on it. In case you can't get it to a mergeable state, just ignore the pre-commit hook (`git commit --no-verify`), push somewhere to your branch and I'll take a look and see if I can pull something usable out of it. Worst case scenario, I'll just re-write it.

**Comment by ghost** [comment]
@dapetcu21  Okay, thank you. I will delete that repo and re-fork it then?

**Comment by dapetcu21** [comment]
That seems to be the easiest solution, yes. But beware that we still don't have endpoints to return the necessary data for that component. I'm also working on a PR with utilities for making API requests, so that's not done yet either.

This component should also work on a ElectionScopeIncomplete value so that it neatly fits in with the rest of the components. Also, check out how to use themable().

Also, know that we have some time constraints, so if you're not done with it in about a couple of days, I'll have to pick it up and do it myself, so if you think you'll take more, better let me do it.

**Comment by ghost** [comment]
Okay @dapetcu21 . I will attempt to push what I have done so far today so that you at least don't have to start from scratch. If I encounter more difficulties, I will inform you that I've thrown the towel in.

**Comment by itsdell** [comment]
@dapetcu21 I have deleted and re-forked the repository, and it seems to me like most of my issues committing (to my own repo, no less) comes from dealing with prettier. I got about a thousand of these errors:

"  124:44   error  Delete `␍`  prettier/prettier " 

I did my best to respect the formatting (no single quotes, double space instead of Tab), but it seems like prettier has a problem with the entire project when I try to commit. Did this ever happen to you as well? Can you help me fix this?

**Comment by ghost** [comment]
I am back. I somehow managed to commit and push the changes to my repo. I have some styling left to do, but so far it looks like this: https://github.com/itsdell/reusable-components

I am afraid that I am a bit at the beginning of my journey and I'm not great with themable.
Is the code satisfactory enough for me to go on?

**Comment by dapetcu21** [comment]
Prettier tells you to delete CR. This means that you checked out using Windows CR LF line endings. I'll add a .gitattributes file to the repo and that should solve that issue

**Comment by dapetcu21** [comment]
Try checking this out: https://github.com/code4romania/reusable-components/pull/29

This should enforce LF line endings everywhere.

**Comment by dapetcu21** [comment]
I looked a bit over your commit. It's a good start. Don't worry about themable. It's easy enough to add it at the end.

What I would recommend, though, would be to look into using some autocomplete library like https://react-select.com or react-autosuggest (that one was great but sad to see it go unmaintained), because for that component autocomplete needs to work and the browser's builtin `<select>` UX doesn't cut it

**Comment by ghost** [comment]
@dapetcu21  Hello, thank you for the feedback. Tomorrow morning I will rewrite the code so as to include the React Select library. I will also try to replace the downward arrow with the cross shape.

I'm sorry about that one message showing the prettier error, I thought I had deleted it! In the end, after running lint -- --fix, everything worked out okay!

**Comment by ghost** [comment]
@dapetcu21 Sorry for being radio silent yesterday. I just made my last commit. If it helps at all anymore, please take a look at it.

**Comment by dapetcu21** [comment]
@itsdell Can you make a draft pull request? It's easier to review that way (especially since its gets deployed on Vercel and you can actually see how it looks).

**Comment by ghost** [comment]
@dapetcu21 yes, hold on

**Comment by dapetcu21** [comment]
I implemented this on friday. @itsdell Thanks for your contribution! I ended up not using it, unfortunately, but thank you nonetheless! 😄
